<?php
/**
 * Mapa editorial das telas públicas. O painel usa este arquivo para separar
 * os textos por página e oferecer uma prévia coerente de cada experiência.
 */
function contentPageDefinitions(): array
{
    return [
        'home' => [
            'label' => 'Página inicial',
            'description' => 'Primeira impressão, experiência da guia e chamadas principais.',
            'preview' => '/index.php',
            'fields' => [
                'home_hero_eyebrow' => ['Sobretítulo da abertura','text','ANCESTRALIDADE • FEITO À MÃO • PRESENÇA'],
                'home_hero_titulo' => ['Título principal','text','Há coisas que a gente não veste.'],
                'home_hero_destaque' => ['Trecho em destaque','text','A gente carrega.'],
                'home_hero_texto' => ['Texto da abertura','textarea','A Estrada da Lua nasce do encontro entre memória, cuidado e criação. Cada peça é construída para ter presença — do primeiro fio ao último detalhe.'],
                'home_process_kicker' => ['Chamada da experiência','text','SUA GUIA, SEU CAMINHO'],
                'home_process_titulo' => ['Título da experiência','text','Uma peça feita para pertencer à sua história.'],
                'home_process_texto' => ['Texto da experiência','textarea','A criação começa na escuta: referências, intenção, cores e detalhes. O orçamento é justo e transparente, mas o centro da experiência é o cuidado com aquilo que você quer receber.'],
                'baralho_teaser_titulo' => ['Chamada do Baralho','text','Há perguntas que não pedem pressa. Pedem presença.'],
                'baralho_teaser_texto' => ['Texto do Baralho','textarea','Um espaço de escuta e reflexão para olhar uma questão por outros ângulos, sem entregar sua autonomia para as cartas.'],
                'home_closing_titulo' => ['Título do fechamento','text','Talvez a sua peça ainda não exista. E isso é a melhor parte.'],
                'home_closing_texto' => ['Texto do fechamento','textarea','Conte sua ideia. A gente transforma referência em matéria, com acompanhamento do começo ao fim.'],
            ],
        ],
        'memorias' => [
            'label' => 'História & memórias',
            'description' => 'Página de trabalhos realizados e narrativa da trajetória.',
            'preview' => '/portfolio.php',
            'fields' => [
                'portfolio_eyebrow' => ['Sobretítulo','text','TRABALHOS REALIZADOS'],
                'portfolio_titulo' => ['Título','textarea',"O que já foi feito\ntambém conta a nossa história."],
                'portfolio_texto' => ['Texto de abertura','textarea','Cada trabalho guarda decisões, encontros e referências diferentes. Esta é a memória visual de peças que já seguiram seus próprios caminhos.'],
                'portfolio_close_kicker' => ['Fechamento · chamada','text','AGORA É A SUA VEZ'],
                'portfolio_close_titulo' => ['Fechamento · título','textarea',"Quer criar algo\nsó seu?"],
                'portfolio_close_texto' => ['Fechamento · texto','textarea','Conte o que você imaginou. Pode mandar cores, medidas e até uma imagem de referência.'],
            ],
        ],
        'loja' => [
            'label' => 'Loja',
            'description' => 'Página que explica os dois caminhos de compra.',
            'preview' => '/loja.php',
            'fields' => [
                'loja_eyebrow' => ['Sobretítulo','text','LOJA ESTRADA DA LUA'],
                'loja_titulo' => ['Título','textarea',"Você pode encontrar\nou começar."],
                'loja_texto' => ['Texto de abertura','textarea','A loja reúne os caminhos de compra sem confundir experiências diferentes: peças que já estão prontas e criações que começam a partir de você.'],
                'loja_pronta_titulo' => ['Card pronta entrega · título','text','Pronta entrega'],
                'loja_pronta_texto' => ['Card pronta entrega · texto','textarea','Peças finalizadas, estoque real e possibilidade de comprar imediatamente.'],
                'loja_personalizada_titulo' => ['Card personalizada · título','text','Feita para você'],
                'loja_personalizada_texto' => ['Card personalizada · texto','textarea','Uma guia personalizada construída a partir de referências, cores, tamanho e conversa.'],
                'loja_acervo_titulo' => ['Título do acervo','text','Explore todas as peças.'],
                'loja_acervo_texto' => ['Texto do acervo','textarea','Use as categorias para navegar. Quando uma peça estiver pronta para envio, isso aparece claramente no card.'],
            ],
        ],
        'pronta' => [
            'label' => 'Pronta entrega',
            'description' => 'Seleção de peças já confeccionadas e disponíveis para compra.',
            'preview' => '/guias-prontas.php',
            'fields' => [
                'pronta_eyebrow' => ['Sobretítulo','text','PRONTA ENTREGA'],
                'pronta_titulo' => ['Título','textarea',"Algumas peças já fizeram\no caminho até aqui."],
                'pronta_texto' => ['Texto de abertura','textarea','Guias disponíveis agora, com fotos reais e estoque visível. Você escolhe a peça e segue direto para o fluxo de compra.'],
                'pronta_nota_titulo' => ['Nota · título','text','Pronta entrega não significa impessoal.'],
                'pronta_nota_texto' => ['Nota · texto','textarea','Cada peça continua sendo preparada com cuidado antes de seguir para você. Aqui, a diferença é só que ela já existe e pode começar o próximo caminho mais rápido.'],
                'pronta_close_kicker' => ['Fechamento · chamada','text','NÃO ENCONTROU A SUA?'],
                'pronta_close_titulo' => ['Fechamento · título','textarea',"Quando a peça certa ainda não existe,\na gente começa pela sua ideia."],
                'pronta_close_texto' => ['Fechamento · texto','textarea','Conte cores, referências, tamanho e o que você deseja sentir quando receber a peça.'],
            ],
        ],
        'baralho' => [
            'label' => 'Baralho Cigano',
            'description' => 'Atmosfera, explicação do oráculo, serviços e chamada final.',
            'preview' => '/baralho-cigano.php',
            'fields' => [
                'baralho_hero_eyebrow' => ['Sobretítulo','text','BARALHO CIGANO • ESCUTA • REFLEXÃO'],
                'baralho_hero_titulo_linha1' => ['Título · linha principal','text','Algumas perguntas não pedem pressa.'],
                'baralho_hero_titulo_destaque' => ['Título · destaque','text','Pedem espaço.'],
                'baralho_hero_texto' => ['Texto de abertura','textarea','Uma leitura pode ser esse intervalo: um momento para organizar o que você sente, enxergar uma situação por outros ângulos e sair com perguntas melhores — não com promessas vazias.'],
                'baralho_deck_nota' => ['Nota do baralho','textarea','Uma experiência simbólica para explorar o baralho. A leitura completa acontece no atendimento.'],
                'baralho_intro_titulo' => ['Título da introdução','textarea',"A leitura abre símbolos.\nVocê continua dono do caminho."],
                'baralho_intro_texto' => ['Texto da introdução','textarea','O Baralho Cigano é usado aqui como instrumento de reflexão e conversa. A proposta é acolher uma questão, observar padrões e possibilidades e construir uma leitura cuidadosa, sem substituir sua autonomia.'],
                'baralho_servicos_titulo' => ['Título dos serviços','textarea',"Uma leitura para o tamanho\ndo que você precisa olhar."],
                'baralho_servicos_texto' => ['Texto dos serviços','textarea','Cada opção tem duração e valor definidos com transparência. Para solicitar uma leitura, você entra na sua conta e o atendimento fica guardado no seu perfil.'],
                'baralho_close_titulo' => ['Fechamento · título','textarea',"Talvez seja hora de dar a ela\num lugar para ser escutada."],
                'baralho_close_texto' => ['Fechamento · texto','textarea','Escolha uma leitura, conte brevemente o que você deseja olhar e acompanhe tudo dentro do seu perfil.'],
                'baralho_hero_btn_primario' => ['Botão principal','text','Escolher minha leitura'],
                'baralho_hero_btn_secundario' => ['Link para carta simbólica','text','Tirar uma carta simbólica →'],
                'baralho_deck_botao' => ['Botão do baralho','text','Embaralhar e tirar uma carta'],
                'baralho_frase' => ['Frase de transição','textarea','“Nem toda resposta precisa prever o futuro. Às vezes, ela só precisa devolver presença ao agora.”'],
                'baralho_intro_kicker' => ['Introdução · chamada','text','UM ORÁCULO, NÃO UMA SENTENÇA'],
                'baralho_valor_1_titulo' => ['Etapa 1 · título','text','Você chega com uma questão'],
                'baralho_valor_1_texto' => ['Etapa 1 · texto','textarea','Não precisa estar perfeitamente formulada. A gente organiza junto.'],
                'baralho_valor_2_titulo' => ['Etapa 2 · título','text','A leitura cria um mapa'],
                'baralho_valor_2_texto' => ['Etapa 2 · texto','textarea','Cartas, símbolos e relações ajudam a olhar para o cenário com outras lentes.'],
                'baralho_valor_3_titulo' => ['Etapa 3 · título','text','Você leva reflexão, não dependência'],
                'baralho_valor_3_texto' => ['Etapa 3 · texto','textarea','O objetivo é sair com mais clareza para decidir por si.'],
                'baralho_servicos_kicker' => ['Serviços · chamada','text','ESCOLHA O TEMPO DA SUA PERGUNTA'],
                'baralho_servico_badge' => ['Serviço em destaque · selo','text','MAIS ESCOLHIDA'],
                'baralho_servico_cta' => ['Serviço · botão','text','Quero esta leitura'],
                'baralho_emocao_kicker' => ['Seção emocional · chamada','text','QUANDO UMA LEITURA PODE FAZER SENTIDO'],
                'baralho_emocao_titulo' => ['Seção emocional · título','textarea',"Quando a cabeça repete a mesma pergunta\ne nenhuma resposta parece suficiente."],
                'baralho_emocao_1_titulo' => ['Situação 1 · título','text','Quando existe uma decisão'],
                'baralho_emocao_1_texto' => ['Situação 1 · texto','textarea','e você quer enxergar melhor o que pesa em cada caminho.'],
                'baralho_emocao_2_titulo' => ['Situação 2 · título','text','Quando algo mudou'],
                'baralho_emocao_2_texto' => ['Situação 2 · texto','textarea','e você ainda está tentando entender o lugar que isso ocupa dentro de você.'],
                'baralho_emocao_3_titulo' => ['Situação 3 · título','text','Quando você quer se escutar'],
                'baralho_emocao_3_texto' => ['Situação 3 · texto','textarea','sem transformar o oráculo em uma autoridade sobre sua vida.'],
                'baralho_close_kicker' => ['Fechamento · chamada','text','SE A PERGUNTA CONTINUA VOLTANDO'],
                'baralho_close_cta' => ['Fechamento · botão','text','Solicitar uma leitura'],
                'baralho_close_etica' => ['Nota ética','textarea','Leituras não substituem orientação médica, psicológica, jurídica ou financeira e não prometem resultados futuros.'],
            ],
        ],
        'perfil' => [
            'label' => 'Perfil & conta',
            'description' => 'Cadastro, preferências e apresentação da área pessoal.',
            'preview' => '/preview-perfil.php',
            'fields' => [
                'conta_hero_eyebrow' => ['Sobretítulo','text','SUA ESTRADA, GUARDADA AQUI'],
                'conta_hero_titulo' => ['Título','textarea',"Uma conta para deixar\na experiência mais sua."],
                'conta_hero_texto' => ['Texto de abertura','textarea','Para comprar, pedir uma peça, solicitar uma leitura ou conversar com a equipe, você entra na sua conta. Navegar e conhecer a Estrada da Lua continua livre.'],
                'conta_cadastro_titulo' => ['Cadastro · título','text','Comece com o essencial.'],
                'conta_preferencias_titulo' => ['Preferências · título','text','Se quiser, conte o que mais te chama atenção'],
                'conta_preferencias_texto' => ['Preferências · apoio','textarea','Opcional. Isso ajuda a personalizar o perfil sem alongar o cadastro.'],
                'conta_marketing_titulo' => ['Marketing · título','text','Quero receber novidades da Estrada da Lua'],
                'conta_marketing_texto' => ['Marketing · apoio','textarea','Ofertas, novos trabalhos e conteúdos. Você pode mudar isso no perfil quando quiser.'],
                'perfil_hero_eyebrow' => ['Perfil logado · sobretítulo','text','MEU PERFIL'],
                'perfil_hero_destaque' => ['Perfil logado · frase','text','Que bom ter você por aqui.'],
                'perfil_hero_texto' => ['Perfil logado · apoio','textarea','Este espaço é seu: pedidos, leituras, preferências e atendimento em um só lugar.'],
                'conta_lateral_titulo' => ['Cadastro · lateral · título','text','Não é só um login.'],
                'conta_lateral_texto' => ['Cadastro · lateral · texto','textarea','Seu perfil reúne compras, encomendas, leituras, atendimento e preferências. A base já fica pronta para recomendações e conteúdos mais pessoais no futuro.'],
                'conta_login_titulo' => ['Login · título','text','Entre na sua estrada.'],
                'conta_login_lateral_titulo' => ['Login · lateral · título','text','Primeira vez por aqui?'],
                'conta_login_lateral_texto' => ['Login · lateral · texto','textarea','Crie sua conta em poucos campos. Você continua escolhendo o que deseja receber e pode alterar suas preferências depois.'],
            ],
        ],
        'atendimento' => [
            'label' => 'Atendimento',
            'description' => 'Central de conversas entre cliente e equipe.',
            'preview' => '/preview-atendimento.php',
            'fields' => [
                'chat_hero_eyebrow' => ['Sobretítulo','text','ATENDIMENTO'],
                'chat_hero_titulo' => ['Título','textarea',"Uma conversa que fica\njunto do seu caminho."],
                'chat_hero_texto' => ['Texto de abertura','textarea','Tire dúvidas, converse sobre sua encomenda e acompanhe decisões sem perder mensagens no meio de outros aplicativos.'],
                'chat_nova_kicker' => ['Nova conversa · chamada','text','NOVA CONVERSA'],
                'chat_nova_titulo' => ['Nova conversa · título','text','Como podemos ajudar?'],
                'chat_lista_kicker' => ['Lista · chamada','text','SUAS CONVERSAS'],
                'chat_lista_titulo' => ['Lista · título','text','Atendimento em um só lugar.'],
            ],
        ],
        'personalizada' => [
            'label' => 'Guia personalizada',
            'description' => 'Formulário de encomenda e narrativa do processo artesanal.',
            'preview' => '/pedido.php?admin_preview=1',
            'fields' => [
                'pedido_eyebrow' => ['Sobretítulo','text','ENCOMENDA PERSONALIZADA'],
                'pedido_titulo' => ['Título','textarea',"Antes de existir nas mãos,\nsua guia começa na intenção."],
                'pedido_texto' => ['Texto de abertura','textarea','Este formulário é o começo de uma conversa. Você traz referências, cores e sensações; a Estrada da Lua transforma isso em uma proposta cuidadosa.'],
                'pedido_como_titulo' => ['Lateral · título','text','Você não precisa saber tudo.'],
                'pedido_como_texto' => ['Lateral · texto','textarea','Preencha o que já tem em mente. O restante é alinhado depois pelo canal escolhido.'],
            ],
        ],
    ];
}
