<?php
require_once __DIR__ . '/includes/auth.php';
require_once __DIR__ . '/../config/database.php';
require_once __DIR__ . '/../config/schema.php';
require_once __DIR__ . '/../includes/functions.php';
ensureFullSchema($pdo);$pageTitle='Financeiro';
$mes=$_GET['mes']??date('Y-m');if(!preg_match('/^\d{4}-\d{2}$/',$mes))$mes=date('Y-m');$inicio=$mes.'-01';$fim=date('Y-m-d',strtotime($inicio.' +1 month'));
$s=$pdo->prepare("SELECT * FROM vendas WHERE data_venda>=? AND data_venda<? ORDER BY data_venda DESC,id DESC");$s->execute([$inicio,$fim]);$vendas=$s->fetchAll();$receita=$custos=$lucro=0;$origens=[];$positivas=$negativas=0;foreach($vendas as &$v){$c=(float)$v['custo_materiais']+(float)$v['custo_tempo']+(float)$v['custo_envio']+(float)$v['outros_custos'];$l=(float)$v['receita']-$c;$v['_custo']=$c;$v['_lucro']=$l;$receita+=(float)$v['receita'];$custos+=$c;$lucro+=$l;$l>=0?$positivas++:$negativas++;if(!isset($origens[$v['origem']]))$origens[$v['origem']]=['receita'=>0,'lucro'=>0,'q'=>0];$origens[$v['origem']]['receita']+=(float)$v['receita'];$origens[$v['origem']]['lucro']+=$l;$origens[$v['origem']]['q']++;}unset($v);$margem=$receita>0?($lucro/$receita*100):0;$ticket=count($vendas)?$receita/count($vendas):0;
require __DIR__ . '/includes/header.php';
?>
<div class="admin-top"><div><span class="section-kicker">RESULTADO DO MÊS</span><h1>Financeiro</h1><p>Veja o que entrou, o que custou e quanto realmente ficou.</p></div><div class="finance-actions"><form method="get"><input type="month" name="mes" value="<?= e($mes) ?>" onchange="this.form.submit()"></form><button class="btn btn-dark" type="button" data-open-sale-modal>+ Registrar venda</button></div></div>
<div class="finance-hero <?= $lucro>=0?'green':'red' ?>" id="financeHero"><div><small>RESULTADO LÍQUIDO</small><strong id="metricProfit"><?= dinheiro($lucro) ?></strong><span id="metricHealth"><?= $lucro>=0?'Fechando no verde':'Fechando no vermelho' ?></span></div><div class="finance-mini"><span>Margem <b id="metricMargin"><?= number_format($margem,1,',','.') ?>%</b></span><span>Ticket médio <b id="metricTicket"><?= dinheiro($ticket) ?></b></span><span>Vendas <b id="metricCount"><?= count($vendas) ?></b></span></div></div>
<div class="stat-grid finance-stats"><article class="stat"><span>Faturamento</span><strong id="metricRevenue"><?= dinheiro($receita) ?></strong><small>Receita bruta do mês</small></article><article class="stat"><span>Custos</span><strong id="metricCosts"><?= dinheiro($custos) ?></strong><small>Materiais + tempo + envio + outros</small></article><article class="stat"><span>Saúde das vendas</span><strong id="metricPositive"><?= $positivas ?>/<?= count($vendas) ?></strong><small id="metricNegative"><?= $negativas ?> venda(s) no vermelho</small></article></div>
<?php if($origens): ?><div class="admin-section-head"><div><span class="section-kicker">DE ONDE VEIO</span><h2>Resultado por frente</h2></div></div><div class="origin-grid"><?php foreach($origens as $origem=>$o): ?><article class="origin-card"><span><?= e($origem) ?></span><strong><?= dinheiro($o['receita']) ?></strong><small><?= $o['q'] ?> venda(s) · lucro <?= dinheiro($o['lucro']) ?></small><div class="origin-bar"><i style="width:<?= min(100,$receita>0?$o['receita']/$receita*100:0) ?>%"></i></div></article><?php endforeach; ?></div><?php endif; ?>
<div class="admin-section-head"><div><span class="section-kicker">VENDA POR VENDA</span><h2>O que deu margem — e o que não deu</h2></div></div><div class="table-wrap finance-table"><table><thead><tr><th>Data</th><th>Origem</th><th>Descrição</th><th>Receita</th><th>Custo</th><th>Lucro</th><th>Margem</th><th></th></tr></thead><tbody id="financeTableBody"><?php foreach($vendas as $v): $mg=(float)$v['receita']>0?$v['_lucro']/(float)$v['receita']*100:0; ?><tr class="<?= $v['_lucro']>=0?'row-green':'row-red' ?>"><td><?= date('d/m',strtotime($v['data_venda'])) ?></td><td><?= e($v['origem']) ?></td><td><strong><?= e($v['descricao']) ?></strong><small><?= e($v['cliente']) ?></small></td><td><?= dinheiro($v['receita']) ?></td><td><?= dinheiro($v['_custo']) ?></td><td><strong><?= dinheiro($v['_lucro']) ?></strong></td><td><?= number_format($mg,1,',','.') ?>%</td><td><a class="table-link" href="<?= BASE_URL ?>/admin/venda.php?id=<?= (int)$v['id'] ?>">Editar</a></td></tr><?php endforeach; ?><?php if(!$vendas): ?><tr id="financeEmpty"><td colspan="8" class="empty-cell">Ainda não há vendas registradas neste mês.</td></tr><?php endif; ?></tbody></table></div>

<div class="ui-modal sale-modal" id="saleModal" aria-hidden="true" role="dialog" aria-modal="true" aria-labelledby="saleModalTitle"><button type="button" class="ui-modal-backdrop" data-close-sale aria-label="Fechar"></button><div class="ui-modal-card sale-modal-card"><button class="coming-close" type="button" data-close-sale aria-label="Fechar">×</button><span class="section-kicker">REGISTRO RÁPIDO</span><h2 id="saleModalTitle">Registrar venda</h2><p>Adicione uma venda sem sair do financeiro. Os indicadores são atualizados assim que o registro for salvo.</p><form action="<?= BASE_URL ?>/admin/venda-api.php" method="post" data-sale-form data-current-month="<?= e($mes) ?>"><div class="form-grid two"><div class="form-group"><label>Origem</label><select name="origem"><option>Guia personalizada</option><option>Produto</option><option>Baralho Cigano</option><option>Outro</option></select></div><div class="form-group"><label>Data</label><input type="date" name="data_venda" value="<?= date('Y-m-d') ?>" required></div><div class="form-group"><label>Cliente</label><input name="cliente"></div><div class="form-group"><label>Descrição</label><input name="descricao" required></div><div class="form-group"><label>Receita</label><input name="receita" inputmode="decimal" required></div><div class="form-group"><label>Custo de materiais</label><input name="custo_materiais" inputmode="decimal"></div><div class="form-group"><label>Custo do tempo</label><input name="custo_tempo" inputmode="decimal"></div><div class="form-group"><label>Custo de envio</label><input name="custo_envio" inputmode="decimal"></div><div class="form-group"><label>Outros custos</label><input name="outros_custos" inputmode="decimal"></div><div class="form-group full"><label>Observações</label><textarea name="observacoes"></textarea></div></div><div class="modal-actions"><button class="btn btn-secondary" type="button" data-close-sale>Cancelar</button><button class="btn btn-dark" type="submit">Salvar venda</button></div></form></div></div>
<?php require __DIR__ . '/includes/footer.php'; ?>
