<?php
require_once __DIR__ . '/includes/auth.php';
require_once __DIR__ . '/../config/database.php';
require_once __DIR__ . '/../config/schema.php';
require_once __DIR__ . '/../includes/functions.php';
ensureFullSchema($pdo);$pageTitle='Precificação';$msg='';$erro='';
$pedidoId=filter_input(INPUT_GET,'pedido',FILTER_VALIDATE_INT);
if($_SERVER['REQUEST_METHOD']==='POST'){
try{$acao=$_POST['acao']??'';
if($acao==='config'){$vals=['valor_cm','valor_hora','custo_embalagem','frete_padrao','margem_percentual','taxa_pagamento_percentual'];$data=[];foreach($vals as $v)$data[$v]=parseMoneyInput($_POST[$v]??0);$s=$pdo->prepare("UPDATE configuracao_precos SET valor_cm=?,valor_hora=?,custo_embalagem=?,frete_padrao=?,margem_percentual=?,taxa_pagamento_percentual=? WHERE id=1");$s->execute(array_values($data));$msg='Parâmetros atualizados.';}
if($acao==='material_add'){$nome=trim($_POST['nome']??'');$un=trim($_POST['unidade']??'unidade');$val=parseMoneyInput($_POST['valor_unitario']??0);if($nome==='')throw new RuntimeException('Informe o nome do material.');$s=$pdo->prepare("INSERT INTO materiais_preco (nome,unidade,valor_unitario) VALUES (?,?,?)");$s->execute([$nome,$un,$val]);$msg='Material adicionado.';}
if($acao==='material_update'){$id=(int)($_POST['id']??0);$val=parseMoneyInput($_POST['valor_unitario']??0);$ativo=!empty($_POST['ativo'])?1:0;$s=$pdo->prepare("UPDATE materiais_preco SET valor_unitario=?,ativo=? WHERE id=?");$s->execute([$val,$ativo,$id]);$msg='Material atualizado.';}
if($acao==='material_delete'){$id=(int)($_POST['id']??0);$s=$pdo->prepare("DELETE FROM materiais_preco WHERE id=?");$s->execute([$id]);$msg='Material excluído.';}
if($acao==='aplicar_pedido'){$pid=(int)($_POST['pedido_id']??0);$config=getConfigPrecos($pdo);$comp=parseMoneyInput($_POST['comprimento']??0);$horas=parseMoneyInput($_POST['horas']??0);$mat=parseMoneyInput($_POST['materiais_total']??0);$env=parseMoneyInput($_POST['envio']??0);$calc=calcularPrecoGuia($config,$comp,$mat,$horas,$env);$s=$pdo->prepare("UPDATE pedidos SET comprimento_cm=?,horas_trabalho=?,custo_materiais_calculado=?,custo_tempo_calculado=?,custo_comprimento_calculado=?,custo_envio_calculado=?,custo_embalagem_calculado=?,preco_sugerido=? WHERE id=?");$s->execute([$comp,$horas,$calc['custoMateriais'],$calc['custoTempo'],$calc['custoComprimento'],$calc['custoEnvio'],$calc['custoEmbalagem'],$calc['sugerido'],$pid]);$msg='Cálculo aplicado ao pedido #'.$pid;$pedidoId=$pid;}
}catch(Throwable $e){$erro=$e->getMessage();}}
$config=getConfigPrecos($pdo);$materiais=$pdo->query("SELECT * FROM materiais_preco ORDER BY ativo DESC,nome")->fetchAll();$pedido=null;if($pedidoId){$s=$pdo->prepare("SELECT * FROM pedidos WHERE id=?");$s->execute([$pedidoId]);$pedido=$s->fetch();}
require __DIR__ . '/includes/header.php';
?>
<div class="admin-top"><div><span class="section-kicker">CUSTO → PREÇO → MARGEM</span><h1>Precificação</h1><p>Altere os parâmetros quando seu custo mudar. O calculador usa sempre os valores atuais.</p></div><?php if($pedido): ?><a class="btn btn-secondary" href="<?= BASE_URL ?>/admin/pedido.php?id=<?= (int)$pedido['id'] ?>">Voltar ao pedido #<?= (int)$pedido['id'] ?></a><?php endif; ?></div>
<?php if($msg): ?><div class="alert"><?= e($msg) ?></div><?php endif; ?><?php if($erro): ?><div class="alert alert-error"><?= e($erro) ?></div><?php endif; ?>
<div class="admin-two-col"><section class="detail-card"><span class="section-kicker">PARÂMETROS GERAIS</span><h2>O que compõe seu preço</h2><form method="post" class="form-grid two"><input type="hidden" name="acao" value="config"><div class="form-group"><label>Custo base por cm</label><input name="valor_cm" value="<?= e($config['valor_cm']) ?>"></div><div class="form-group"><label>Valor do seu tempo / hora</label><input name="valor_hora" value="<?= e($config['valor_hora']) ?>"></div><div class="form-group"><label>Embalagem por pedido</label><input name="custo_embalagem" value="<?= e($config['custo_embalagem']) ?>"></div><div class="form-group"><label>Frete padrão</label><input name="frete_padrao" value="<?= e($config['frete_padrao']) ?>"></div><div class="form-group"><label>Margem-alvo (%)</label><input name="margem_percentual" value="<?= e($config['margem_percentual']) ?>"></div><div class="form-group"><label>Taxa de pagamento (%)</label><input name="taxa_pagamento_percentual" value="<?= e($config['taxa_pagamento_percentual']) ?>"></div><div class="form-group full"><button class="btn btn-dark">Salvar parâmetros</button></div></form><p class="formula-note">Preço sugerido = custos ÷ (1 − margem − taxa). Assim a margem não é tratada apenas como um acréscimo simples.</p></section>
<section class="detail-card calculator-card"><span class="section-kicker">CALCULADORA</span><h2><?= $pedido?'Pedido #'.(int)$pedido['id']:'Simular uma guia' ?></h2><form method="post" id="priceCalc"><input type="hidden" name="acao" value="aplicar_pedido"><input type="hidden" name="pedido_id" value="<?= (int)($pedido['id']??0) ?>"><input type="hidden" name="materiais_total" id="materialsTotalInput" value="0"><div class="form-grid two"><div class="form-group"><label>Comprimento (cm)</label><input id="calcLength" name="comprimento" type="number" step="0.1" value="<?= e((string)($pedido['comprimento_cm']??60)) ?>"></div><div class="form-group"><label>Tempo de produção (horas)</label><input id="calcHours" name="horas" type="number" step="0.1" value="<?= e((string)($pedido['horas_trabalho']??2)) ?>"></div><div class="form-group full"><label>Envio</label><input id="calcShipping" name="envio" type="number" step="0.01" value="<?= e((string)($pedido['custo_envio_calculado']??$config['frete_padrao'])) ?>"></div></div><div class="material-calc-list"><strong>Materiais usados</strong><?php foreach($materiais as $m): if(!$m['ativo'])continue; ?><label><span><?= e($m['nome']) ?><small><?= dinheiro($m['valor_unitario']) ?> / <?= e($m['unidade']) ?></small></span><input class="material-qty" type="number" min="0" step="0.01" value="0" data-price="<?= (float)$m['valor_unitario'] ?>"></label><?php endforeach; ?></div><div class="calc-result"><div><span>Custo estimado</span><strong id="calcCost">R$ 0,00</strong></div><div class="primary"><span>Preço sugerido</span><strong id="calcPrice">R$ 0,00</strong></div></div><?php if($pedido): ?><button class="btn btn-dark btn-wide">Aplicar este cálculo ao pedido</button><?php else: ?><small class="calc-help">Abra esta calculadora a partir de um pedido para salvar a simulação nele.</small><?php endif; ?></form></section></div>
<div class="admin-section-head"><div><span class="section-kicker">TABELA MUTÁVEL</span><h2>Materiais</h2></div></div><div class="material-admin-grid"><section class="form-card"><form method="post"><input type="hidden" name="acao" value="material_add"><div class="form-group"><label>Novo material</label><input name="nome" placeholder="Ex.: conta de cristal" required></div><div class="form-grid two"><div class="form-group"><label>Unidade</label><input name="unidade" placeholder="unidade, metro, pacote..."></div><div class="form-group"><label>Valor unitário</label><input name="valor_unitario" required></div></div><button class="btn btn-dark">Adicionar material</button></form></section><div class="table-wrap"><table><thead><tr><th>Material</th><th>Valor</th><th>Ativo</th><th></th></tr></thead><tbody><?php foreach($materiais as $m): ?><tr><td><strong><?= e($m['nome']) ?></strong><small>por <?= e($m['unidade']) ?></small></td><td><form method="post" class="inline-admin-form"><input type="hidden" name="acao" value="material_update"><input type="hidden" name="id" value="<?= (int)$m['id'] ?>"><input name="valor_unitario" value="<?= e($m['valor_unitario']) ?>"><label class="mini-check"><input type="checkbox" name="ativo" <?= $m['ativo']?'checked':'' ?>> ativo</label><button class="btn btn-secondary">Salvar</button></form></td><td><?= $m['ativo']?'Sim':'Não' ?></td><td><form method="post" data-confirm="Excluir este material?"><input type="hidden" name="acao" value="material_delete"><input type="hidden" name="id" value="<?= (int)$m['id'] ?>"><button class="table-link danger-link">Excluir</button></form></td></tr><?php endforeach; ?></tbody></table></div></div>
<script>
(function(){const cfg={cm:<?= (float)$config['valor_cm'] ?>,hour:<?= (float)$config['valor_hora'] ?>,pack:<?= (float)$config['custo_embalagem'] ?>,margin:<?= (float)$config['margem_percentual'] ?>,fee:<?= (float)$config['taxa_pagamento_percentual'] ?>};const qs=s=>document.querySelector(s),qsAll=s=>[...document.querySelectorAll(s)];function n(el){return parseFloat(el.value||0)||0}function money(v){return v.toLocaleString('pt-BR',{style:'currency',currency:'BRL'})}function calc(){let mats=0;qsAll('.material-qty').forEach(i=>mats+=n(i)*parseFloat(i.dataset.price||0));qs('#materialsTotalInput').value=mats.toFixed(2);const cost=n(qs('#calcLength'))*cfg.cm+n(qs('#calcHours'))*cfg.hour+n(qs('#calcShipping'))+cfg.pack+mats;const div=Math.max(.05,1-(cfg.margin+cfg.fee)/100);qs('#calcCost').textContent=money(cost);qs('#calcPrice').textContent=money(cost/div)}document.querySelectorAll('#priceCalc input').forEach(i=>i.addEventListener('input',calc));calc();})();
</script>
<?php require __DIR__ . '/includes/footer.php'; ?>
