<?php
require_once __DIR__ . '/config/database.php';
require_once __DIR__ . '/config/schema.php';
require_once __DIR__ . '/includes/functions.php';
ensureFullSchema($pdo);
$pageTitle='Início';
$historia=$pdo->query("SELECT * FROM historia ORDER BY id ASC LIMIT 1")->fetch();
$trabalhos=$pdo->query("SELECT * FROM portfolio ORDER BY data_cadastro DESC LIMIT 5")->fetchAll();
$produtos=$pdo->query("SELECT * FROM produtos ORDER BY pronta_entrega DESC, id DESC LIMIT 6")->fetchAll();
$prontas=$pdo->query("SELECT * FROM produtos WHERE tipo_produto='Guia' AND pronta_entrega=1 AND estoque>0 ORDER BY id DESC LIMIT 3")->fetchAll();
require __DIR__ . '/includes/header.php';
?>
<section class="hero-ancestral hero-v5">
    <div class="hero-v5-orbit orbit-a"></div><div class="hero-v5-orbit orbit-b"></div><div class="hero-v5-thread"></div>
    <div class="container hero-v5-inner">
        <span class="eyebrow light" data-content-key="home_hero_eyebrow"><?= e(siteContent($pdo,'home_hero_eyebrow','ANCESTRALIDADE • FEITO À MÃO • PRESENÇA')) ?></span>
        <h1><span data-content-key="home_hero_titulo"><?= e(siteContent($pdo,'home_hero_titulo','Há coisas que a gente não veste.')) ?></span><br><em data-content-key="home_hero_destaque" data-typing data-typing-speed="52"><?= e(siteContent($pdo,'home_hero_destaque','A gente carrega.')) ?></em></h1>
        <p class="hero-lead" data-content-key="home_hero_texto"><?= e(siteContent($pdo,'home_hero_texto','A Estrada da Lua nasce do encontro entre memória, cuidado e criação. Cada peça é construída para ter presença — do primeiro fio ao último detalhe.')) ?></p>
        <div class="hero-actions"><a class="btn btn-brand-gold" href="<?= BASE_URL ?>/pedido.php">Criar minha guia</a><a class="text-link" href="<?= BASE_URL ?>/loja.php#pronta-entrega">Descobrir peças prontas ↗</a></div>
        <div class="hero-proof hero-proof-v5"><div><strong>01</strong><span>Escuta antes da criação</span></div><div><strong>02</strong><span>Acabamento feito com cuidado</span></div><div><strong>03</strong><span>Atendimento que continua depois do pedido</span></div></div>
    </div>
</section>
<section class="manifesto-strip"><div class="container manifesto-line"><span>MEMÓRIA</span><i>✦</i><span>MATÉRIA</span><i>✦</i><span>CAMINHO</span><i>✦</i><span>PRESENÇA</span></div></section>

<section class="section home-paths-section">
<div class="container">
    <div class="section-heading split-heading"><div><span class="section-kicker">TRÊS FORMAS DE ENTRAR</span><h2 class="display-title">Entenda a Estrada da Lua<br>sem precisar procurar.</h2></div><p>Você pode encontrar uma peça que já existe, começar algo pensado para você ou abrir espaço para uma leitura. Cada caminho tem seu próprio ritmo.</p></div>
    <div class="home-paths-grid">
        <a class="home-path-card ready" href="<?= BASE_URL ?>/guias-prontas.php"><span>01 · PRONTA ENTREGA</span><div class="path-card-art bead-path"><i></i><i></i><i></i><i></i><i></i></div><h3>Encontrar algo que já está pronto.</h3><p>Peças finalizadas, fotos reais e disponibilidade visível para você escolher com calma.</p><strong>Ver peças disponíveis →</strong></a>
        <a class="home-path-card custom" href="<?= BASE_URL ?>/pedido.php"><span>02 · FEITA PARA VOCÊ</span><div class="path-card-art thread-path"><i></i><b></b></div><h3>Começar pela sua própria referência.</h3><p>Cores, intenção, tamanho e detalhes ganham forma numa criação construída em conversa com você.</p><strong>Contar minha ideia →</strong></a>
        <a class="home-path-card oracle" href="<?= BASE_URL ?>/baralho-cigano.php"><span>03 · BARALHO CIGANO</span><div class="path-card-art mini-deck"><i></i><i></i><i></i><b>☾</b></div><h3>Dar espaço para uma pergunta.</h3><p>Uma experiência de escuta e reflexão que preserva sua autonomia e convida a olhar por outros ângulos.</p><strong>Entrar no oráculo →</strong></a>
    </div>
</div>
</section>

<section class="section story-section"><div class="container story-layout"><div class="section-kicker">NOSSA HISTÓRIA</div><div><h2 class="display-title"><?= e($historia['titulo']??'Uma história que continua sendo tecida') ?></h2><div class="story-text"><?= nl2br(e($historia['texto']??'A Estrada da Lua é um espaço de criação onde cada peça nasce do encontro entre referência, escuta e trabalho manual.')) ?></div><a class="text-link dark" href="<?= BASE_URL ?>/portfolio.php">Ver o que já nasceu por aqui →</a></div></div></section>

<section class="section process-section"><div class="container"><div class="section-heading split-heading"><div><span class="section-kicker" data-content-key="home_process_kicker"><?= e(siteContent($pdo,'home_process_kicker','SUA GUIA, SEU CAMINHO')) ?></span><h2 class="display-title" data-content-key="home_process_titulo"><?= e(siteContent($pdo,'home_process_titulo','Uma peça feita para pertencer à sua história.')) ?></h2></div><p data-content-key="home_process_texto"><?= e(siteContent($pdo,'home_process_texto','A criação começa na escuta: referências, intenção, cores e detalhes. O orçamento é justo e transparente, mas o centro da experiência é o cuidado com aquilo que você quer receber.')) ?></p></div><div class="process-grid"><article class="process-card"><span>01</span><h3>Você traz a referência</h3><p>Pode ser uma cor, uma memória, uma intenção, uma fotografia ou só a sensação que você quer carregar.</p></article><article class="process-card"><span>02</span><h3>A gente compõe com cuidado</h3><p>Materiais, proporção, acabamento e presença são pensados para que a peça faça sentido como um todo.</p></article><article class="process-card"><span>03</span><h3>Você acompanha o caminho</h3><p>Do pedido à entrega, existe atendimento, conversa e acompanhamento sem transformar a experiência em algo impessoal.</p></article></div><div class="process-cta quality-cta"><div><small>CUIDADO QUE VOCÊ PERCEBE NOS DETALHES</small><strong>O valor é justo e transparente. O que fica na memória é a experiência inteira.</strong></div><a class="btn btn-dark" href="<?= BASE_URL ?>/pedido.php">Criar comigo</a></div></div></section>

<?php if($prontas): ?><section id="pronta-entrega" class="section ready-home-section"><div class="container"><div class="section-heading split-heading"><div><span class="section-kicker">JÁ EXISTEM. ESTÃO AQUI.</span><h2 class="display-title">Peças prontas para começar<br>um novo caminho.</h2></div><div><p>Algumas criações já estão finalizadas e disponíveis. Se uma delas te encontrar primeiro, você pode escolher e seguir direto para a compra.</p><a class="text-link dark" href="<?= BASE_URL ?>/guias-prontas.php">Ver toda a pronta entrega →</a></div></div><div class="ready-guide-grid"><?php foreach($prontas as $g): ?><article class="ready-guide-card"><a href="<?= BASE_URL ?>/produto.php?id=<?= (int)$g['id'] ?>"><div class="ready-guide-image"><?php if($g['imagem_principal']): ?><img src="<?= BASE_URL.'/'.e($g['imagem_principal']) ?>" alt="<?= e($g['nome']) ?>"><?php else: ?><div class="image-placeholder"><span>Estrada<br>da Lua</span></div><?php endif; ?><span class="ready-badge">Disponível agora</span></div></a><div class="ready-guide-body"><h3><?= e($g['nome']) ?></h3><div class="ready-guide-bottom"><strong><?= dinheiro($g['preco']) ?></strong><a class="btn btn-dark" href="<?= BASE_URL ?>/comprar-pronto.php?id=<?= (int)$g['id'] ?>">Comprar</a></div></div></article><?php endforeach; ?></div></div></section><?php endif; ?>

<section class="oracle-home-teaser"><div class="container oracle-home-grid"><div class="oracle-home-symbol"><span></span><i></i><b>☾</b></div><div><span class="section-kicker light">BARALHO CIGANO</span><h2 data-content-key="baralho_teaser_titulo"><?= e(siteContent($pdo,'baralho_teaser_titulo','Há perguntas que não pedem pressa. Pedem presença.')) ?></h2><p data-content-key="baralho_teaser_texto"><?= e(siteContent($pdo,'baralho_teaser_texto','Um espaço de escuta e reflexão para olhar uma questão por outros ângulos, sem entregar sua autonomia para as cartas.')) ?></p><a class="btn btn-brand-gold" href="<?= BASE_URL ?>/baralho-cigano.php">Entrar neste caminho →</a></div></div></section>

<?php if($trabalhos): ?><section class="section memories-section"><div class="container"><div class="section-heading"><span class="section-kicker light">MEMÓRIAS QUE JÁ PASSARAM POR AQUI</span><h2 class="display-title light">Peças feitas para pessoas reais,<br>em caminhos diferentes.</h2></div><div class="editorial-grid"><?php foreach($trabalhos as $i=>$item): ?><article class="editorial-card <?= $i===0?'featured':'' ?>"><a href="<?= BASE_URL ?>/portfolio.php"><div class="editorial-image"><?php if($item['imagem']): ?><img src="<?= BASE_URL.'/'.e($item['imagem']) ?>" alt="<?= e($item['titulo']) ?>"><?php else: ?><div class="image-placeholder"><span>Estrada<br>da Lua</span></div><?php endif; ?><span class="editorial-number"><?= str_pad((string)($i+1),2,'0',STR_PAD_LEFT) ?></span></div><h3><?= e($item['titulo']) ?></h3><p><?= e(excerpt($item['descricao'],100)) ?></p></a></article><?php endforeach; ?></div></div></section><?php endif; ?>

<?php $feedbackLimit=6;$feedbackOrigem=null;require __DIR__ . '/includes/feedbacks-section.php'; ?>

<section class="section future-home-section"><div class="container"><div class="section-heading split-heading"><div><span class="section-kicker">A ESTRADA CONTINUA</span><h2 class="display-title">Alguns encontros ainda<br>estão ganhando forma.</h2></div><p>Conteúdo também pode ser uma forma de cuidado. Estes espaços estão sendo preparados para aprofundar histórias, processos e conversas.</p></div><div class="future-home-grid"><button type="button" data-coming-soon="Caderno da Lua" data-coming-text="Textos, bastidores, histórias de criação, cuidados com as peças e reflexões da Estrada da Lua. Estamos preparando este espaço."><small>01 · LEITURA</small><strong>Caderno da Lua</strong><span>Histórias, processos e símbolos para continuar a experiência além da compra.</span><b>Conhecer em breve →</b></button><button type="button" data-coming-soon="Vozes da Estrada" data-coming-text="Um podcast para transformar conversa em companhia. Os primeiros episódios ainda estão em produção."><small>02 · ESCUTA</small><strong>Vozes da Estrada</strong><span>Conversas para ouvir devagar, em outros momentos do seu caminho.</span><b>Ouvir em breve →</b></button></div></div></section>

<section class="closing-cta"><div class="container closing-grid"><div><span class="section-kicker light">QUANDO NÃO EXISTE PRONTO, A GENTE CRIA</span><h2 data-content-key="home_closing_titulo"><?= e(siteContent($pdo,'home_closing_titulo','Talvez a sua peça ainda não exista. E isso é a melhor parte.')) ?></h2></div><div><p data-content-key="home_closing_texto"><?= e(siteContent($pdo,'home_closing_texto','Conte sua ideia. A gente transforma referência em matéria, com acompanhamento do começo ao fim.')) ?></p><div class="actions"><a class="btn btn-brand-gold" href="<?= BASE_URL ?>/pedido.php">Quero uma guia personalizada</a><?php if($clienteHeader): ?><a class="btn btn-outline-light" href="<?= BASE_URL ?>/chat.php">Conversar com a equipe</a><?php endif; ?></div></div></div></section>
<?php require __DIR__ . '/includes/footer.php'; ?>
