<?php
require_once __DIR__ . '/config/database.php';
require_once __DIR__ . '/config/schema.php';
require_once __DIR__ . '/includes/functions.php';
ensureFullSchema($pdo);
$pageTitle='Loja';
$categoria=filter_input(INPUT_GET,'categoria',FILTER_VALIDATE_INT);
$categorias=$pdo->query("SELECT * FROM categorias ORDER BY nome")->fetchAll();
$sql="SELECT p.*,c.nome categoria FROM produtos p LEFT JOIN categorias c ON c.id=p.categoria_id";$params=[];
if($categoria){$sql.=" WHERE p.categoria_id=?";$params[]=$categoria;}
$sql.=" ORDER BY p.pronta_entrega DESC, p.estoque DESC, p.id DESC";
$st=$pdo->prepare($sql);$st->execute($params);$produtos=$st->fetchAll();
$prontas=array_values(array_filter($produtos,fn($p)=>!empty($p['pronta_entrega'])&&(int)$p['estoque']>0));
require __DIR__ . '/includes/header.php';
?>
<section class="page-hero shop-hero"><div class="container page-hero-grid"><div><span class="eyebrow" data-content-key="loja_eyebrow"><?= e(siteContent($pdo,'loja_eyebrow','LOJA ESTRADA DA LUA')) ?></span><h1 data-content-key="loja_titulo"><?= nl2br(e(siteContent($pdo,'loja_titulo',"Você pode encontrar\nou começar."))) ?></h1></div><p data-content-key="loja_texto"><?= e(siteContent($pdo,'loja_texto','A loja reúne os caminhos de compra sem confundir experiências diferentes: peças que já estão prontas e criações que começam a partir de você.')) ?></p></div></section>
<section class="section shop-chooser"><div class="container"><div class="shop-choice-grid"><a class="shop-choice-card ready" href="#pronta-entrega"><small>QUERO ALGO QUE JÁ EXISTE</small><h2 data-content-key="loja_pronta_titulo"><?= e(siteContent($pdo,'loja_pronta_titulo','Pronta entrega')) ?></h2><p data-content-key="loja_pronta_texto"><?= e(siteContent($pdo,'loja_pronta_texto','Peças finalizadas, estoque real e possibilidade de comprar imediatamente.')) ?></p><strong>Ver peças prontas →</strong></a><a class="shop-choice-card custom" href="<?= BASE_URL ?>/pedido.php"><small>QUERO ALGO PENSADO PARA MIM</small><h2 data-content-key="loja_personalizada_titulo"><?= e(siteContent($pdo,'loja_personalizada_titulo','Feita para você')) ?></h2><p data-content-key="loja_personalizada_texto"><?= e(siteContent($pdo,'loja_personalizada_texto','Uma guia personalizada construída a partir de referências, cores, tamanho e conversa.')) ?></p><strong>Começar uma criação →</strong></a></div></div></section>

<?php if($prontas): ?><section id="pronta-entrega" class="section ready-store-block"><div class="container"><div class="section-heading split-heading"><div><span class="section-kicker">PRONTA ENTREGA</span><h2 class="display-title">Já feitas. Ainda esperando<br>por quem vai carregá-las.</h2></div><a class="text-link dark" href="<?= BASE_URL ?>/guias-prontas.php">Ver seleção completa →</a></div><div class="ready-guide-grid"><?php foreach(array_slice($prontas,0,3) as $p): ?><article class="ready-guide-card"><a href="<?= BASE_URL ?>/produto.php?id=<?= (int)$p['id'] ?>"><div class="ready-guide-image"><?php if($p['imagem_principal']): ?><img src="<?= BASE_URL.'/'.e($p['imagem_principal']) ?>" alt="<?= e($p['nome']) ?>"><?php else: ?><div class="image-placeholder"><span>Estrada<br>da Lua</span></div><?php endif; ?><span class="ready-badge">Disponível agora</span></div></a><div class="ready-guide-body"><small><?= e($p['categoria']??'Peça') ?></small><h3><?= e($p['nome']) ?></h3><div class="ready-guide-bottom"><strong><?= dinheiro($p['preco']) ?></strong><a class="btn btn-dark" href="<?= BASE_URL ?>/comprar-pronto.php?id=<?= (int)$p['id'] ?>">Comprar</a></div></div></article><?php endforeach; ?></div></div></section><?php endif; ?>

<section class="section shop-page"><div class="container"><div class="section-heading split-heading"><div><span class="section-kicker">ACERVO DA LOJA</span><h2 class="display-title" data-content-key="loja_acervo_titulo"><?= e(siteContent($pdo,'loja_acervo_titulo','Explore todas as peças.')) ?></h2></div><p data-content-key="loja_acervo_texto"><?= e(siteContent($pdo,'loja_acervo_texto','Use as categorias para navegar. Quando uma peça estiver pronta para envio, isso aparece claramente no card.')) ?></p></div><?php if($categorias): ?><div class="filter-row"><a class="filter-pill <?= !$categoria?'active':'' ?>" href="<?= BASE_URL ?>/loja.php">Todas</a><?php foreach($categorias as $c): ?><a class="filter-pill <?= $categoria===(int)$c['id']?'active':'' ?>" href="?categoria=<?= (int)$c['id'] ?>"><?= e($c['nome']) ?></a><?php endforeach; ?></div><?php endif; ?><?php if($produtos): ?><div class="product-grid shop-grid"><?php foreach($produtos as $p): ?><article class="product-card"><a href="<?= BASE_URL ?>/produto.php?id=<?= (int)$p['id'] ?>"><div class="product-image"><?php if($p['imagem_principal']): ?><img src="<?= BASE_URL.'/'.e($p['imagem_principal']) ?>" alt="<?= e($p['nome']) ?>"><?php else: ?><div class="image-placeholder"><span>Estrada<br>da Lua</span></div><?php endif; ?><?php if(!empty($p['pronta_entrega']) && (int)$p['estoque']>0): ?><span class="ready-badge">Pronta entrega</span><?php else: ?><span class="custom-badge">Sob encomenda</span><?php endif; ?><span class="product-view">Descobrir ↗</span></div><div class="product-meta"><div><small><?= e($p['categoria']??'Peça') ?></small><h3><?= e($p['nome']) ?></h3></div><strong><?= dinheiro($p['preco']) ?></strong></div></a></article><?php endforeach; ?></div><?php else: ?><div class="empty-state"><h2>Nenhuma peça nesta categoria ainda.</h2><a class="btn btn-dark" href="<?= BASE_URL ?>/pedido.php">Começar uma criação</a></div><?php endif; ?></div></section>
<?php $feedbackOrigem='Loja';$feedbackLimit=4;require __DIR__ . '/includes/feedbacks-section.php'; ?>
<?php require __DIR__ . '/includes/footer.php'; ?>
