<?php
require_once __DIR__ . '/config/app.php';
require_once __DIR__ . '/config/database.php';
require_once __DIR__ . '/config/schema.php';
require_once __DIR__ . '/includes/functions.php';
ensureFullSchema($pdo);
$pageTitle='Guia personalizada';$sucesso=false;$erro='';$codigo='';startClientSession();$adminPreview=!empty($_GET['admin_preview']) && !empty($_SESSION['usuario_id']);$cliente=$adminPreview?['id'=>0,'nome'=>'Cliente','email'=>'cliente@exemplo.com','telefone'=>'(41) 99999-9999']:requireClient($pdo);
$produtoId=filter_input(INPUT_GET,'produto',FILTER_VALIDATE_INT);$produto=null;
if($produtoId){$s=$pdo->prepare("SELECT * FROM produtos WHERE id=?");$s->execute([$produtoId]);$produto=$s->fetch();if($produto && !empty($produto['pronta_entrega']) && (int)$produto['estoque']>0){setFlash('Esta peça já está pronta. Você foi direcionado para a compra direta.','success');header('Location: '.BASE_URL.'/comprar-pronto.php?id='.(int)$produto['id']);exit;}}
if($_SERVER['REQUEST_METHOD']==='POST' && !$adminPreview){
try{
$nome=trim($_POST['nome']??'');$telefone=trim($_POST['telefone']??'');$email=trim($_POST['email']??'');$tipo=trim($_POST['tipo_pedido']??'Guia personalizada');$linha=trim($_POST['linha_referencia']??'');$tamanho=trim($_POST['tamanho']??'');$cores=trim($_POST['cores']??'');$materiais=trim($_POST['materiais']??'');$q=max(1,(int)($_POST['quantidade']??1));$orc=trim($_POST['faixa_orcamento']??'');$prazo=trim($_POST['prazo_desejado']??'');$pref=trim($_POST['preferencia_contato']??'WhatsApp');$obs=trim($_POST['observacoes']??'');$arquivo=null;
if($nome===''||$telefone===''||$cores==='')throw new RuntimeException('Preencha seu nome, telefone e pelo menos uma referência de cor.');
if(!empty($_FILES['arquivo_referencia']['name']))$arquivo=uploadImagem($_FILES['arquivo_referencia'],'pedidos');
$codigo=generateTrackingCode('EDL');
$s=$pdo->prepare("INSERT INTO pedidos (cliente_id,nome_cliente,telefone,email,tipo_pedido,linha_referencia,tamanho,cores,materiais,quantidade,faixa_orcamento,prazo_desejado,preferencia_contato,arquivo_referencia,observacoes,codigo_acompanhamento) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)");
$s->execute([$cliente['id']??null,$nome,$telefone,$email,$tipo,$linha,$tamanho,$cores,$materiais,$q,$orc,$prazo?:null,$pref,$arquivo,$obs,$codigo]);$pedidoId=(int)$pdo->lastInsertId();
$produtoPost=filter_input(INPUT_POST,'produto_id',FILTER_VALIDATE_INT);if($produtoPost){$p=$pdo->prepare("SELECT preco FROM produtos WHERE id=?");$p->execute([$produtoPost]);$preco=$p->fetchColumn();if($preco!==false){$it=$pdo->prepare("INSERT INTO pedido_itens (pedido_id,produto_id,quantidade,valor) VALUES (?,?,?,?)");$it->execute([$pedidoId,$produtoPost,$q,$preco]);}}
rememberTracking('pedido',$codigo);$sucesso=true;
}catch(Throwable $e){$erro=$e->getMessage();}}
require __DIR__ . '/includes/header.php';
?>
<section class="request-hero"><div class="container request-hero-grid"><div><span class="eyebrow" data-content-key="pedido_eyebrow"><?= e(siteContent($pdo,'pedido_eyebrow','ENCOMENDA PERSONALIZADA')) ?></span><h1 data-content-key="pedido_titulo"><?= nl2br(e(siteContent($pdo,'pedido_titulo',"Antes de existir nas mãos,\nsua guia começa na intenção."))) ?></h1></div><p data-content-key="pedido_texto"><?= e(siteContent($pdo,'pedido_texto','Este formulário é o começo de uma conversa. Você traz referências, cores e sensações; a Estrada da Lua transforma isso em uma proposta cuidadosa.')) ?></p></div></section>
<section class="section request-section"><div class="container request-layout"><aside class="request-aside"><span class="section-kicker">COMO FUNCIONA</span><h2 data-content-key="pedido_como_titulo"><?= e(siteContent($pdo,'pedido_como_titulo','Você não precisa saber tudo.')) ?></h2><p data-content-key="pedido_como_texto"><?= e(siteContent($pdo,'pedido_como_texto','Preencha o que já tem em mente. O restante é alinhado depois pelo canal escolhido.')) ?></p><ol class="request-steps"><li><span>1</span><div><strong>Conte o que você imagina</strong><small>Uma cor, uma memória ou uma referência já é um começo.</small></div></li><li><span>2</span><div><strong>A criação ganha forma</strong><small>Materiais, proporção e acabamento são pensados com cuidado.</small></div></li><li><span>3</span><div><strong>Você acompanha o caminho</strong><small>Receba um código e veja cada etapa até a entrega.</small></div></li></ol><?php if($produto): ?><div class="request-product"><small>VOCÊ VEIO DESTA PEÇA</small><strong><?= e($produto['nome']) ?></strong><span><?= dinheiro($produto['preco']) ?></span></div><?php endif; ?></aside><div class="request-form-wrap">
<?php if($sucesso): ?><div class="success-panel big-success"><span class="success-mark">✓</span><div><strong>Seu pedido chegou até nós.</strong><p>Guarde seu código de acompanhamento: <b><?= e($codigo) ?></b>.</p><div class="actions"><a class="btn btn-dark" href="<?= BASE_URL ?>/meus-pedidos.php">Ver meus pedidos</a><?php if(!empty($pedidoId)): ?><a class="btn btn-secondary" href="<?= BASE_URL ?>/chat.php?pedido=<?= (int)$pedidoId ?>">Falar com a equipe</a><?php endif; ?></div></div></div><?php else: ?><?php if($erro): ?><div class="alert alert-error"><?= e($erro) ?></div><?php endif; ?>
<form class="request-form" method="post" enctype="multipart/form-data"><?php if($produto): ?><input type="hidden" name="produto_id" value="<?= (int)$produto['id'] ?>"><?php endif; ?>
<div class="form-section-title"><span>01</span><div><strong>Quem está fazendo o pedido?</strong><small>Seus dados são usados para atendimento desta solicitação.</small></div></div><div class="form-grid two"><div class="form-group"><label>Seu nome *</label><input name="nome" value="<?= e($_POST['nome']??$cliente['nome']??'') ?>" required></div><div class="form-group"><label>WhatsApp / telefone *</label><input name="telefone" value="<?= e($_POST['telefone']??$cliente['telefone']??'') ?>" required></div><div class="form-group"><label>E-mail</label><input type="email" name="email" value="<?= e($_POST['email']??$cliente['email']??'') ?>"></div><div class="form-group"><label>Prefere falar por</label><select name="preferencia_contato"><option>WhatsApp</option><option>E-mail</option><option>Ligação</option></select></div></div>
<div class="form-section-title"><span>02</span><div><strong>Como você imagina sua guia?</strong><small>Não existe resposta certa. Estas informações orientam a criação.</small></div></div><div class="form-grid two"><div class="form-group"><label>Tipo de peça</label><select name="tipo_pedido"><option>Guia personalizada</option><option>Fio de contas</option><option>Peça inspirada em referência</option><option>Outro</option></select></div><div class="form-group"><label>Linha, entidade ou referência <span class="optional">opcional</span></label><input name="linha_referencia" value="<?= e($_POST['linha_referencia']??'') ?>"></div><div class="form-group"><label>Tamanho / comprimento</label><input name="tamanho" value="<?= e($_POST['tamanho']??'') ?>" placeholder="Ex.: 60 cm"></div><div class="form-group"><label>Quantidade</label><input type="number" min="1" name="quantidade" value="<?= e($_POST['quantidade']??'1') ?>"></div><div class="form-group full"><label>Cores desejadas *</label><input name="cores" value="<?= e($_POST['cores']??'') ?>" required></div><div class="form-group full"><label>Materiais, contas ou acabamentos</label><input name="materiais" value="<?= e($_POST['materiais']??'') ?>"></div></div>
<div class="form-section-title"><span>03</span><div><strong>Prazo, orçamento e referências</strong><small>Ajuda a transformar sua ideia em uma proposta viável.</small></div></div><div class="form-grid two"><div class="form-group"><label>Faixa de orçamento</label><select name="faixa_orcamento"><option value="">Prefiro receber uma proposta</option><option>Até R$ 100</option><option>R$ 100 a R$ 200</option><option>R$ 200 a R$ 350</option><option>Acima de R$ 350</option></select></div><div class="form-group"><label>Data desejada</label><input type="date" name="prazo_desejado"></div><div class="form-group full"><label>Foto de referência</label><input class="file-input" type="file" name="arquivo_referencia" accept=".jpg,.jpeg,.png,.webp"></div><div class="form-group full"><label>Me conte qualquer detalhe que faltou</label><textarea name="observacoes"></textarea></div></div>
<label class="consent-row"><input type="checkbox" required><span>Confirmo que as informações podem ser usadas pela Estrada da Lua para analisar e responder esta solicitação.</span></label><button class="btn btn-dark btn-submit">Enviar minha solicitação →</button><p class="form-footnote">O envio é uma solicitação de orçamento e não confirma automaticamente a produção.</p></form><?php endif; ?>
</div></div></section>
<?php require __DIR__ . '/includes/footer.php'; ?>
